#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2022 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg@outlook.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    max_column = 120
    textwidth = 118

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30


[[layers]]
name = "github"

[[layers]]
  name = "git"

[[layers]]
  name = "sudo"

[[layers]]
  name = "edit"

[[layers]]
    name = 'core'
    filetree_show_hidden = true
    enable_smooth_scrolling = true

[[layers]]
name="lang#sh"

[[layers]]
    name = 'lang#c'

[[layers]]
  name="lang#python"
  python_file_head = [
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]
  # enable_typeinfo = true
  # format_on_save = true

[[layers]]
  name = "lang#ipynb"
   
[[layers]]
  name="lang#markdown"
  enabled_formater=["remark", "prettier"]
# yarn global add prettier
# npm -g install remark
# enable=false

[[layers]]
name="tools"

[[layers]]
  name = "chinese"

[[layers]]
  # need pip install notedown
  name="lang#ipynb"

[[layers]]
name="lang#html"

[[layers]]
name="lang#latex"

[[layers]]
name="lang#toml"

[[layers]]
  name="test"

[[layers]]
name="default"

[[layers]]
  name = "format"


