-- last  Modified:   2026-01-16 16:07:10
-- vim.g.loaded_perl_provider = 0
-- require("user.plugins.friendly-snippets").print_current_directory()
-- vim.g.luasnip_log_level = "trace" -- or "debug"
-- require("user.plugins.friendly-snippets").setup()
-- require('user.plugins.luasnip_config')
